name: Publish
on:
  workflow_dispatch

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Python 3.10
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.10.11
          architecture: x64

      - name: Build and pack
        run: python3 build.py both
        
      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ecsta-firefox.zip
          path: dist/ecsta-firefox.zip

      - name: Upload Chromium Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ecsta-chromium.zip
          path: dist/ecsta-chromium.zip

  release:
    name: Upload to GitHub Releases
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: ecsta-chromium.zip
          path: release
          
      - uses: actions/download-artifact@v2
        with:
          name: ecsta-firefox.zip
          path: release    

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'manifest.xpi.json'
          prop_path: 'version'

      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: ${{steps.version.outputs.prop}} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.version.outputs.prop}} 
          name: Ecsta - Build ${{steps.version.outputs.prop}} 
          draft: false
          prerelease: false
          body_path: .github/release.md
          files: |
            release/ecsta-chromium.zip
            release/ecsta-firefox.zip
  upload-xpi:
    name: Upload to Mozilla Store
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ecsta-firefox.zip
          path: release

      - uses: maoserr/firefox_extension_publish@v1.0.4
        with:
          # Extension ID.
          firefox_extension_id: Ecsta@kckarnige.github.io
          # API key from Mozilla
          api_key: ${{ secrets.JWT_ISSUER }}
          # API secret from Mozilla
          api_secret: ${{ secrets.JWT_SECRET }}
          # Zip file for firefox extension
          file: release/ecsta-firefox.zip

  upload-crx:
    name: Upload to Chrome Web Store
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ecsta-chromium.zip
          path: release

      - uses: maoserr/chrome_extension_publish@v1.0.3
        with:
          chrome_extension_id: jpdnfbcjclmhlebikidldibdlgjindpl
          client_id: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
          refresh_token: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
          client_secret: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
          publish: true
          file: release/ecsta-chromium.zip
