name: Test Release
on:
  workflow_dispatch

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13.7
          architecture: x64

      - name: Build and pack
        run: python3 build.py both
        
      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecsta-firefox.zip
          path: dist/ecsta-firefox.zip
          
      - name: Upload Chromium Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecsta-chromium.zip
          path: dist/ecsta-chromium.zip

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v4
        with:
          name: ecsta-chromium.zip
          path: release
          
      - uses: actions/download-artifact@v4
        with:
          name: ecsta-firefox.zip
          path: release    

      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'manifest.xpi.json'
          prop_path: 'version'

      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: devbuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get shortened hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: devbuild
          name: Ecsta - Test build (${{ steps.vars.outputs.sha_short }})
          draft: false
          prerelease: true
          body_path: .github/test_release.md
          files: |
            release/ecsta-chromium.zip
            release/ecsta-firefox.zip
